name: Greetings

on: [pull_request, issues]

jobs:
  greeting: Hello Hello! Thanks for working on this!
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Right, this is the first issue'
        pr-message: 'Good Luck!'
